site_name: My Docs

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - admonition

nav:
  - Home:
    - Welcome: home/welcome.md
    - Getting Started: home/getting_started.md
  - About: about.md
  - Research:
    - Research1: research/research1.md
    - Research2: research/research2.md
  - Development:
    - Architecture: development/architecture.md
    - Coding Practices: development/coding_practices.md
